name: test
on:
 push:
  branches:
     - master
     - develop
     
jobs:
   build:
    name: Running ubuntu Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm test
