name: fithub action simple 
on:
 pull_request:
 push:
  branches:
     - master
     - develop
     
jobs:
   test:
    name: Running Unit Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm test
