name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag my-image-name:hello
       DOCKER_BUILDKIT=1 docker build -f Dockerfile -t firoj0786/mm:MM-${{ github.sha }} --build-arg 
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
       image: firoj0786/demo-app
       context: .
       push: true
       tags:
          user/image:latest
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       if: contains('refs/heads/main refs/heads/rc refs/heads/uat refs/heads/test refs/heads/develop',github.ref)
        

       
       

