name: Docker Image 


on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main,develop ]

jobs:

  build:
      

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build_push_tag of develop
     
      if: contains('refs/heads/develop',github.ref)
      env:      
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      
     
      run: |
            
             docker login -u $USERNAME -p $PASSWORD
             docker build -t firoj0786/mm:${{ github.sha }} -f Dockerfile .  
             docker push firoj0786/mm:${{ github.sha }}

    - uses: actions/checkout@v2
    - name: build_push_tag of main
     
      if: contains('refs/heads/main',github.ref)
      env:      
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      
     
      run: |
            
             docker login -u $USERNAME -p $PASSWORD
             docker build -t firoj0786/mm:${{ github.sha }} -f Dockerfile .  
             docker push firoj0786/mm:${{ github.sha }}    
             
  deploy:
 
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: deploy app
      if: contains('refs/heads/develop',github.ref)
      env:
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      run: |
      
              docker login -u $USERNAME -p $PASSWORD
              docker build -t firoj0786/mm:${{ github.sha }} -f Dockerfile .   
              docker push firoj0786/mm:${{ github.sha }}
              docker-compose -f docker-compose.yml  up -d 

            
  
    - uses: actions/checkout@v2
    - name: deploy app1
      if: contains('refs/heads/main',github.ref)
      env:
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      run: |
      
              docker login -u $USERNAME -p $PASSWORD
              docker build -t firoj0786/mm:${{ github.sha }} -f Dockerfile .   
              docker push firoj0786/mm:${{ github.sha }}
              docker-compose -f docker-compose2.yml up -d 
