name: Docker Image CI


on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main,develop ]

jobs:

  build:
      

    runs-on: self-hosted
    steps:
    
    - name: build_push_tag of develop
     
      if: contains('refs/heads/develop',github.ref)
      env:      
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      
     
      run: |
             docker login -u $USERNAME -p $PASSWORD
             docker build -t firoj0786/mm:${{ github.tag -t firoj0786/app }} -f Dockerfile .  
             docker push firoj0786/mm:${{ github.tag -t firoj0786/app }}
             image_name: "firoj0786"
             image_tag: "latest"
      
             
  deploy:
 
    runs-on: self-hosted
    steps:
    
    - name: deploy app
      if: contains('refs/heads/main',github.ref)
      env:
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      run: |
              docker login -u $USERNAME -p $PASSWORD
              docker build -t firoj0786/mm:${{ github.tag -t firoj0786/app }} -f Dockerfile .   
              docker push firoj0786/mm:${{ github.tag -t firoj0786/app }}
        
              docker-compose up -d
              
              
